/** Declaration file generated by dts-gen */

export const data: {
  baac: {
    code: string;
    color: string;
    nice_name: string;
    official_name: string;
    official_name_thai: string;
  };
  bay: {
    code: string;
    color: string;
    nice_name: string;
    official_name: string;
    official_name_thai: string;
  };
  bbl: {
    code: string;
    color: string;
    nice_name: string;
    official_name: string;
    official_name_thai: string;
  };
  cimb: {
    code: string;
    color: string;
    nice_name: string;
    official_name: string;
    official_name_thai: string;
  };
  gsb: {
    code: string;
    color: string;
    nice_name: string;
    official_name: string;
    official_name_thai: string;
  };
  icbc: {
    code: string;
    color: string;
    nice_name: string;
    official_name: string;
    official_name_thai: string;
  };
  kbank: {
    code: string;
    color: string;
    nice_name: string;
    official_name: string;
    official_name_thai: string;
  };
  kk: {
    code: string;
    color: string;
    nice_name: string;
    official_name: string;
    official_name_thai: string;
  };
  ktb: {
    code: string;
    color: string;
    nice_name: string;
    official_name: string;
    official_name_thai: string;
  };
  lhb: {
    code: string;
    color: string;
    nice_name: string;
    official_name: string;
    official_name_thai: string;
  };
  scb: {
    code: string;
    color: string;
    nice_name: string;
    official_name: string;
    official_name_thai: string;
  };
  tbank: {
    code: string;
    color: string;
    nice_name: string;
    official_name: string;
    official_name_thai: string;
  };
  tmb: {
    code: string;
    color: string;
    nice_name: string;
    official_name: string;
    official_name_thai: string;
  };
  uob: {
    code: string;
    color: string;
    nice_name: string;
    official_name: string;
    official_name_thai: string;
  };
};

export function Get(key: any): any;

export function listKey(): any;
